

mysql:
docker run --name mysql -p 3308:3306  -e MYSQL_ROOT_PASSWORD=123456 -d mysql
docker run -d -e MYSQL_ROOT_PASSWORD=admin --name mysql -v /data/mysql/my.cnf:/etc/mysql/my.cnf -v /data/mysql/data:/var/lib/mysql -p 3306:3306 mysql 

docker run --name mysql1 -p 3309:3306 -e MYSQL_ROOT_PASSWORD=123456  -v /data/mysql/data1:/var/lib/mysql -d mysql


docker run -p 9980:80 --name mynginx -v /nginx/www:/www -v /nginx/conf/nginx.conf:/etc/nginx/nginx.conf -v /nginx/logs:/wwwlogs  -d nginx

docker run --name mysql1 -p 3309:3306 -e MYSQL_ROOT_PASSWORD=123456  -v /data/mysql/data_typecho:/var/lib/mysql -d mysql

docker run -p 9981:80 --name typecho -v /etc/apache/www/:/var/www/html -v /etc/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf -v /etc/apache/logs/:/usr/local/apache2/logs/ -d eboraas/apache-php
